/**
 * Product Constants
 *
 * Mock product data for new arrivals section.
 * In production, this would come from an API or database.
 */

import { Product, CategoryFilter } from '../types/product';

export const NEW_ARRIVALS: Product[] = [
  {
    id: 1,
    name: 'The Classic Knit Polo',
    price: 12.00,
    image: 'placeholder',
    colors: 7,
    category: 'T-Shirt',
    collection: 'Essential',
    badge: 'New Release',
  },
  {
    id: 2,
    name: 'Zip Jacket',
    price: 16.25,
    image: 'placeholder',
    colors: 2,
    category: 'Jacket',
    collection: 'Premium',
  },
  {
    id: 3,
    name: 'The Utility Jacket',
    price: 25.00,
    image: 'placeholder',
    colors: 3,
    category: 'Jacket',
    collection: 'Essential',
  },
  {
    id: 4,
    name: 'The Suede Jacket',
    price: 18.75,
    image: 'placeholder',
    colors: 2,
    category: 'Jacket',
    collection: 'Premium',
  },
];

export const EVERYDAY_WEAR: Product[] = [
  {
    id: 5,
    name: 'Classic Navy Jacket',
    price: 89.00,
    image: 'placeholder',
    colors: 3,
    category: 'Jacket',
    collection: 'Essential',
  },
  {
    id: 6,
    name: 'Leather Bomber Jacket',
    price: 149.00,
    image: 'placeholder',
    colors: 2,
    category: 'Jacket',
    collection: 'Premium',
  },
  {
    id: 7,
    name: 'Minimalist Jacket',
    price: 95.00,
    image: 'placeholder',
    colors: 4,
    category: 'Jacket',
    collection: 'Essential',
  },
  {
    id: 8,
    name: 'Oversized Bomber',
    price: 125.00,
    image: 'placeholder',
    colors: 2,
    category: 'Jacket',
    collection: 'Premium',
  },
  {
    id: 9,
    name: 'Black Bomber Jacket',
    price: 135.00,
    image: 'placeholder',
    colors: 1,
    category: 'Jacket',
    collection: 'Heritage',
  },
  {
    id: 10,
    name: 'Navy Varsity Jacket',
    price: 110.00,
    image: 'placeholder',
    colors: 2,
    category: 'Jacket',
    collection: 'Essential',
  },
  {
    id: 11,
    name: 'Grey Essential Polo',
    price: 45.00,
    image: 'placeholder',
    colors: 5,
    category: 'T-Shirt',
    collection: 'Essential',
  },
  {
    id: 12,
    name: 'Beige Zip Jacket',
    price: 98.00,
    image: 'placeholder',
    colors: 3,
    category: 'Jacket',
    collection: 'Essential',
  },
  {
    id: 13,
    name: 'Sand Utility Jacket',
    price: 105.00,
    image: 'placeholder',
    colors: 2,
    category: 'Jacket',
    collection: 'Premium',
  },
];

export const CATEGORY_FILTERS: CategoryFilter[] = [
  { id: 'jacket', label: 'Jacket', value: 'Jacket' },
  { id: 'tshirt', label: 'T-Shirt', value: 'T-Shirt' },
  { id: 'pants', label: 'Pants', value: 'Pants' },
  { id: 'shoes', label: 'Shoes', value: 'Shoes' },
];

// Men's Products
export const MEN_PRODUCTS: Product[] = [
  {
    id: 14,
    name: "Men's Essential T-Shirt",
    price: 29.99,
    image: 'placeholder',
    colors: 4,
    category: 'T-Shirt',
    collection: 'Essential',
    description: 'A classic everyday t-shirt made from premium cotton.',
    type: 'T-Shirts',
    material: 'Cotton',
    availableSizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    availableColors: ['Black', 'White', 'Navy', 'Gray'],
  },
  {
    id: 15,
    name: "Classic Denim Jacket",
    price: 89.00,
    image: 'placeholder',
    colors: 2,
    category: 'Jacket',
    collection: 'Heritage',
    badge: 'New Release',
    type: 'Jackets',
    material: 'Denim',
    availableSizes: ['S', 'M', 'L', 'XL'],
    availableColors: ['Navy', 'Black'],
  },
  {
    id: 16,
    name: "Slim Fit Chinos",
    price: 59.99,
    image: 'placeholder',
    colors: 5,
    category: 'Pants',
    collection: 'Essential',
    type: 'Pants',
    material: 'Cotton',
    availableSizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    availableColors: ['Beige', 'Navy', 'Black', 'Gray', 'Brown'],
  },
  {
    id: 17,
    name: "Wool Blend Coat",
    price: 149.00,
    image: 'placeholder',
    colors: 3,
    category: 'Jacket',
    collection: 'Premium',
    type: 'Jackets',
    material: 'Wool',
    availableSizes: ['S', 'M', 'L', 'XL'],
    availableColors: ['Black', 'Navy', 'Gray'],
  },
  {
    id: 18,
    name: "Crew Neck Sweater",
    price: 45.00,
    image: 'placeholder',
    colors: 6,
    category: 'T-Shirt',
    collection: 'Essential',
    type: 'Shirts',
    material: 'Cotton',
    availableSizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    availableColors: ['Black', 'White', 'Navy', 'Gray', 'Beige', 'Brown'],
  },
  {
    id: 19,
    name: "Utility Cargo Pants",
    price: 69.99,
    image: 'placeholder',
    colors: 3,
    category: 'Pants',
    collection: 'Premium',
    type: 'Pants',
    material: 'Synthetic',
    availableSizes: ['S', 'M', 'L', 'XL', 'XXL'],
    availableColors: ['Black', 'Beige', 'Navy'],
  },
  {
    id: 20,
    name: "Puffer Jacket",
    price: 119.00,
    image: 'placeholder',
    colors: 4,
    category: 'Jacket',
    collection: 'Essential',
    type: 'Jackets',
    material: 'Synthetic',
    availableSizes: ['S', 'M', 'L', 'XL', 'XXL'],
    availableColors: ['Black', 'Navy', 'Gray', 'Beige'],
  },
  {
    id: 21,
    name: "Cotton Polo Shirt",
    price: 39.99,
    image: 'placeholder',
    colors: 5,
    category: 'T-Shirt',
    collection: 'Essential',
    type: 'Shirts',
    material: 'Cotton',
    availableSizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    availableColors: ['White', 'Navy', 'Black', 'Beige', 'Gray'],
  },
  {
    id: 22,
    name: "Tailored Trousers",
    price: 79.99,
    image: 'placeholder',
    colors: 4,
    category: 'Pants',
    collection: 'Premium',
    type: 'Pants',
    material: 'Wool',
    availableSizes: ['S', 'M', 'L', 'XL'],
    availableColors: ['Black', 'Navy', 'Gray', 'Beige'],
  },
  {
    id: 23,
    name: "Bomber Jacket",
    price: 99.00,
    image: 'placeholder',
    colors: 3,
    category: 'Jacket',
    collection: 'Heritage',
    type: 'Jackets',
    material: 'Synthetic',
    availableSizes: ['S', 'M', 'L', 'XL', 'XXL'],
    availableColors: ['Black', 'Navy', 'Brown'],
  },
  {
    id: 24,
    name: "V-Neck T-Shirt",
    price: 24.99,
    image: 'placeholder',
    colors: 7,
    category: 'T-Shirt',
    collection: 'Essential',
    type: 'T-Shirts',
    material: 'Cotton',
    availableSizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    availableColors: ['Black', 'White', 'Navy', 'Gray', 'Beige', 'Brown', 'Cream'],
  },
  {
    id: 25,
    name: "Track Pants",
    price: 49.99,
    image: 'placeholder',
    colors: 4,
    category: 'Pants',
    collection: 'Essential',
    type: 'Pants',
    material: 'Synthetic',
    availableSizes: ['S', 'M', 'L', 'XL', 'XXL'],
    availableColors: ['Black', 'Navy', 'Gray', 'Beige'],
  },
];

// Women's Products
export const WOMEN_PRODUCTS: Product[] = [
  {
    id: 26,
    name: "Silk Blouse",
    price: 79.99,
    image: 'placeholder',
    colors: 5,
    category: 'T-Shirt',
    collection: 'Premium',
    badge: 'New Arrival',
    type: 'Tops',
    material: 'Silk',
    availableSizes: ['XXS', 'XS', 'S', 'M', 'L', 'XL'],
    availableColors: ['White', 'Black', 'Beige', 'Cream', 'Blush'],
  },
  {
    id: 27,
    name: "Cashmere Cardigan",
    price: 129.00,
    image: 'placeholder',
    colors: 4,
    category: 'Jacket',
    collection: 'Premium',
    type: 'Jackets',
    material: 'Cashmere',
    availableSizes: ['XS', 'S', 'M', 'L', 'XL'],
    availableColors: ['Beige', 'Navy', 'Black', 'Cream'],
  },
  {
    id: 28,
    name: "High-Waist Trousers",
    price: 69.99,
    image: 'placeholder',
    colors: 3,
    category: 'Pants',
    collection: 'Essential',
    type: 'Bottoms',
    material: 'Cotton',
    availableSizes: ['XXS', 'XS', 'S', 'M', 'L', 'XL'],
    availableColors: ['Black', 'Navy', 'Beige'],
  },
  {
    id: 29,
    name: "Linen Summer Dress",
    price: 89.00,
    image: 'placeholder',
    colors: 6,
    category: 'T-Shirt',
    collection: 'Essential',
    type: 'Dresses',
    material: 'Linen',
    availableSizes: ['XXS', 'XS', 'S', 'M', 'L', 'XL'],
    availableColors: ['White', 'Beige', 'Navy', 'Cream', 'Blush', 'Black'],
  },
  {
    id: 30,
    name: "Trench Coat",
    price: 159.00,
    image: 'placeholder',
    colors: 2,
    category: 'Jacket',
    collection: 'Heritage',
    type: 'Jackets',
    material: 'Cotton',
    availableSizes: ['XS', 'S', 'M', 'L', 'XL'],
    availableColors: ['Beige', 'Black'],
  },
  {
    id: 31,
    name: "Fitted Blazer",
    price: 119.00,
    image: 'placeholder',
    colors: 4,
    category: 'Jacket',
    collection: 'Premium',
    type: 'Jackets',
    material: 'Wool',
    availableSizes: ['XXS', 'XS', 'S', 'M', 'L', 'XL'],
    availableColors: ['Black', 'Navy', 'Beige', 'Cream'],
  },
  {
    id: 32,
    name: "Wide Leg Pants",
    price: 74.99,
    image: 'placeholder',
    colors: 5,
    category: 'Pants',
    collection: 'Essential',
    type: 'Bottoms',
    material: 'Linen',
    availableSizes: ['XXS', 'XS', 'S', 'M', 'L', 'XL'],
    availableColors: ['Black', 'White', 'Beige', 'Navy', 'Cream'],
  },
  {
    id: 33,
    name: "Ribbed Knit Top",
    price: 44.99,
    image: 'placeholder',
    colors: 7,
    category: 'T-Shirt',
    collection: 'Essential',
    type: 'Tops',
    material: 'Cotton',
    availableSizes: ['XXS', 'XS', 'S', 'M', 'L', 'XL'],
    availableColors: ['Black', 'White', 'Beige', 'Navy', 'Cream', 'Blush', 'Brown'],
  },
  {
    id: 34,
    name: "Leather Jacket",
    price: 189.00,
    image: 'placeholder',
    colors: 2,
    category: 'Jacket',
    collection: 'Premium',
    type: 'Jackets',
    material: 'Leather',
    availableSizes: ['XS', 'S', 'M', 'L', 'XL'],
    availableColors: ['Black', 'Brown'],
  },
  {
    id: 35,
    name: "Midi Skirt",
    price: 59.99,
    image: 'placeholder',
    colors: 4,
    category: 'Pants',
    collection: 'Essential',
    type: 'Bottoms',
    material: 'Synthetic',
    availableSizes: ['XXS', 'XS', 'S', 'M', 'L', 'XL'],
    availableColors: ['Black', 'Navy', 'Beige', 'Brown'],
  },
  {
    id: 36,
    name: "Wrap Blouse",
    price: 54.99,
    image: 'placeholder',
    colors: 5,
    category: 'T-Shirt',
    collection: 'Essential',
    type: 'Tops',
    material: 'Silk',
    availableSizes: ['XXS', 'XS', 'S', 'M', 'L', 'XL'],
    availableColors: ['White', 'Black', 'Beige', 'Cream', 'Blush'],
  },
  {
    id: 37,
    name: "Cropped Denim Jacket",
    price: 79.00,
    image: 'placeholder',
    colors: 3,
    category: 'Jacket',
    collection: 'Heritage',
    type: 'Jackets',
    material: 'Denim',
    availableSizes: ['XXS', 'XS', 'S', 'M', 'L', 'XL'],
    availableColors: ['Navy', 'Black', 'White'],
  },
];

export const products: Product[] = [...NEW_ARRIVALS, ...EVERYDAY_WEAR, ...MEN_PRODUCTS, ...WOMEN_PRODUCTS];
